version: '3.1'

services:
  docs:
    image: mesosphere/dcos-docs-site
    build:
      context: .
      dockerfile: "./docker/Dockerfile.${ENV}"
      args:
        nginx_dir: ./docker/nginx
        git_branch: ${GIT_BRANCH}
        algolia_update: ${ALGOLIA_UPDATE}
        algolia_private_key: ${ALGOLIA_PRIVATE_KEY}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - docs-build:/src/build

volumes:
  docs-build:
